/**
 * Created by liqingguo on 2018/12/3.
 */
export const AUTHSUCCESS = 'AUTHSUCCESS';
export const AUTHERROR = 'AUTHERROR';
export const UPDATEUSERINFO='UPDATEUSERINFO';
export const RESETUSERINFO='RESETUSERINFO';
export const UPDATEUSERLIST='UPDATEUSERLIST';
export const RESETUSERLIST='RESETUSERLIST';